### ISSUE TITLE
Clone in SettingsTabProfile.java and SettingsTabUser.java detected by PMD CPD

### ISSUE THREAD

**Issue by zahrarasoulifar** [rilling/argoumlFall2024#35]
**Describe the Clone**
There is duplicated code in the SettingsTabProfile.java and SettingsTabUser.java files within the buildPanel() methods. The duplicated code is responsible for creating a warning panel that includes a warning label and a link button to the project settings.

**Location of the Clones**
File 1: argoumlFall2024/src/argouml-app/src/org/argouml/uml/ui/SettingsTabProfile.java
The duplicated code is located in the buildPanel() method, starting at line 126 and ending at line 139.
File 2: argoumlFall2024/src/argouml-app/src/org/argouml/uml/ui/SettingsTabUser.java
The duplicated code is located in the buildPanel() method, starting at line 94 and ending at line 107.

**Clone Type**
This is a Type 1 clone, as the code is duplicated with no changes to variables, comments, or structure. It is a literal copy-paste of code in multiple places.

**Expected Outcome**
Refactor the duplicated code by creating a new helper class (WarningPanel) to encapsulate the shared logic. Replace the duplicated code in both SettingsTabProfile and SettingsTabUser with instances of this new component to eliminate redundancy while maintaining the existing functionality.

Updated code in SettingsTabProfile.java:
![image](https://github.com/user-attachments/assets/1b9a73fb-2d8e-4685-97bf-b4d3c9dac0eb)

Updated code in SettingsTabUser.java:
![image](https://github.com/user-attachments/assets/805fac66-9fbf-42f4-92dc-02828f1acf95)

WarningPanel.java class added for duplicate code fragment:
![image](https://github.com/user-attachments/assets/bd2c16e9-43e3-4a60-a21d-1d4904509c0c)

**Comment by vishnurajendran** [comment]
resolved in PR https://github.com/rilling/argoumlFall2024/pull/43
