### ISSUE TITLE
SSRF Vulnerability in XMiReaderImpl Class

### ISSUE THREAD

**Issue by thuhinkhanna** [rilling/argoumlFall2024#73]
**Describe the Software Vulnerability**

The copySource methd in the XMiReaderImpl class uses the openStream() function allowing a potential SSRF vulnerability.

**Type of Vulnerability**

SSRF vulnerabilities allows malicious actors to make illegal requests to servers. This might lead to unauthorized access, data exposure and more.

**CVE**

CWE-918 and CWE-73

**Expected outcome**

To validate the links entered by user before creating a Open Stream. This should reduce the possibility of an SSRF attack.

**Code before refactoring**
`String systemId = input.getSystemId();
  if (systemId != null) {
      input = new InputSource(new URL(systemId).openStream());
      }
  InputStream in = input.getByteStream();`

**Comment by vishnurajendran** [comment]
merged with PR #86
